INSERT INTO items (name) VALUES ('protein powder');
INSERT INTO items (name) VALUES ('flour');
INSERT INTO items (name) VALUES ('milk');
INSERT INTO items (name) VALUES ('pizza crust');
INSERT INTO items (name) VALUES ('monkfruit sweetener');
INSERT INTO items (name) VALUES ('egg whites');
INSERT INTO items (name) VALUES ('carrots');
INSERT INTO items (name) VALUES ('water');
INSERT INTO items (name) VALUES ('spam');
INSERT INTO items (name) VALUES ('mascarpone cheese');
INSERT INTO items (name) VALUES ('toilet cleaner');
INSERT INTO items (name) VALUES ('cough syrup');
INSERT INTO items (name) VALUES ('lady fingers');
INSERT INTO items (name) VALUES ('strawberries');
INSERT INTO items (name) VALUES ('sazon seasoning');
INSERT INTO items (name) VALUES ('smoked paprika');
INSERT INTO items (name) VALUES ('cilantro');
INSERT INTO items (name) VALUES ('culantro');
INSERT INTO items (name) VALUES ('cumin');
INSERT INTO items (name) VALUES ('curry paste');
INSERT INTO items (name) VALUES ('garlic paste');
INSERT INTO items (name) VALUES ('bell peppers');
INSERT INTO items (name) VALUES ('chickpeas');
INSERT INTO items (name) VALUES ('pam spray');
INSERT INTO items (name) VALUES ('canned beans');
INSERT INTO items (name) VALUES ('rice');
INSERT INTO items (name) VALUES ('greek yogurt');
INSERT INTO items (name) VALUES ('sugarfree juice');
INSERT INTO items (name) VALUES ('blueberries');
INSERT INTO items (name) VALUES ('enchilada sauce');
INSERT INTO items (name) VALUES ('tortillas');
INSERT INTO items (name) VALUES ('brush');
INSERT INTO items (name) VALUES ('paper cups');
INSERT INTO items (name) VALUES ('makeup wipes');
INSERT INTO items (name) VALUES ('panko crumbs');
INSERT INTO items (name) VALUES ('ham');
INSERT INTO items (name) VALUES ('freezer bags');
INSERT INTO items (name) VALUES ('clamps');
INSERT INTO items (name) VALUES ('batteries');
INSERT INTO items (name) VALUES ('toothpaste');
INSERT INTO items (name) VALUES ('cocoa powder');
INSERT INTO items (name) VALUES ('broom');
INSERT INTO items (name) VALUES ('mushrooms');
INSERT INTO items (name) VALUES ('beef tenderloin');
INSERT INTO items (name) VALUES ('prosciutto');
INSERT INTO items (name) VALUES ('puff pasty');
INSERT INTO items (name) VALUES ('thyme leaves');
INSERT INTO items (name) VALUES ('ibuprofen');
INSERT INTO items (name) VALUES ('chicken nuggets');
INSERT INTO items (name) VALUES ('candy canes');
INSERT INTO items (name) VALUES ('wrapping paper');
INSERT INTO items (name) VALUES ('soy sauce');
INSERT INTO items (name) VALUES ('sponges');
INSERT INTO items (name) VALUES ('hot cocoa');
INSERT INTO items (name) VALUES ('better than buillon');
INSERT INTO items (name) VALUES ('coke zero');
INSERT INTO items (name) VALUES ('piping bags');
INSERT INTO items (name) VALUES ('grapes');
INSERT INTO items (name) VALUES ('bread');
INSERT INTO items (name) VALUES ('potatoes');
INSERT INTO items (name) VALUES ('malanga');
INSERT INTO items (name) VALUES ('marshmallows');
INSERT INTO items (name) VALUES ('salt');
INSERT INTO items (name) VALUES ('pepper');
INSERT INTO items (name) VALUES ('dijon mustard');
INSERT INTO items (name) VALUES ('beef broth');
INSERT INTO items (name) VALUES ('chips');
INSERT INTO items (name) VALUES ('cream of tartar');
INSERT INTO items (name) VALUES ('reese''s cup');
INSERT INTO items (name) VALUES ('sponges');
INSERT INTO items (name) VALUES ('melatonin');
INSERT INTO items (name) VALUES ('sugar');
INSERT INTO items (name) VALUES ('i can''t believe it''s not butter');
INSERT INTO items (name) VALUES ('picanha');
INSERT INTO items (name) VALUES ('fennel seeds');
INSERT INTO items (name) VALUES ('gummies');
INSERT INTO items (name) VALUES ('cookies');
INSERT INTO items (name) VALUES ('parchment paper');
INSERT INTO items (name) VALUES ('corn starch');
INSERT INTO items (name) VALUES ('leeks');
INSERT INTO items (name) VALUES ('hand soap');
INSERT INTO items (name) VALUES ('paper towels');
INSERT INTO items (name) VALUES ('toilet paper');
INSERT INTO items (name) VALUES ('parsley');
INSERT INTO items (name) VALUES ('spinach');
INSERT INTO items (name) VALUES ('mozazarella cheese');
INSERT INTO items (name) VALUES ('butane fuel');
INSERT INTO items (name) VALUES ('soap');
INSERT INTO items (name) VALUES ('eggs');
INSERT INTO items (name) VALUES ('onion');
INSERT INTO items (name) VALUES ('salmon');
INSERT INTO items (name) VALUES ('canned tuna');
INSERT INTO items (name) VALUES ('pizza rolls');
INSERT INTO items (name) VALUES ('frozen pizza');
INSERT INTO items (name) VALUES ('capri suns');
INSERT INTO items (name) VALUES ('fruit snacks');
INSERT INTO items (name) VALUES ('bacon');
INSERT INTO items (name) VALUES ('pasta');
INSERT INTO items (name) VALUES ('hummus');
INSERT INTO items (name) VALUES ('lemons');
INSERT INTO items (name) VALUES ('hot sauce');
INSERT INTO items (name) VALUES ('pesto');
INSERT INTO items (name) VALUES ('limes');
INSERT INTO items (name) VALUES ('mayonnaise');
INSERT INTO items (name) VALUES ('caramel M&Ms ');
INSERT INTO items (name) VALUES ('gummy worms');