INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('1', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('2', 'Pharmacy');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('3', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('4', 'Rear Center');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('5', 'Deli');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('6', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('7', 'Eggs');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('8', 'Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('9', 'Aisle 10');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('10', 'Aisle 3');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('11', 'Deli');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('12', 'Aisle 8');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('13', 'Pharmacy');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('14', 'Dry Grocery');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('15', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('16', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('17', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('18', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('19', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('20', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('21', 'Aisle 3');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('22', 'Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('23', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('24', 'Aisle 5');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('25', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('26', 'Aisle 5');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('27', 'Aisle 5');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('28', 'Rear Center');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('29', 'Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('30', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('31', 'Aisle 3');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('32', 'Aisle 3');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('33', 'Pharmacy');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('34', 'Aisle 9');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('35', 'Pharmacy');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('36', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('37', 'Aisle 1');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('38', 'Aisle 9');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('39', 'item not found');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('40', 'Aisle 7');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('41', 'Pharmacy');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('42', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('43', 'Aisle 8');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('44', 'Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('45', 'Fresh Meat');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('46', 'Deli');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('47', 'Aisle 13');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('48', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('49', 'Pharmacy');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('50', 'Aisle 12');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('51', 'seasonal item');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('52', 'Housewares');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('53', 'Aisle 3');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('55', 'Aisle 2');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('56', 'Aisle 3');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('57', 'Aisle 10');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('58', 'item not found');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('59', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('60', 'Dry Grocery');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('61', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('62', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('63', 'Aisle 3');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('64', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('65', 'Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('66', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('67', 'Aisle 3');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('68', 'Aisle 11');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('69', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('70', 'Dry Grocery');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('71', 'Aisle 8');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('72', 'Pharmacy');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('73', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('74', 'Rear Center');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('75', 'Fresh Meat');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('76', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('77', 'Dry Grocery');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('78', 'Aisle 6');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('79', 'Aisle 9');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('80', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('81', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('82', 'Pharmacy');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('83', 'Aisle 9');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('84', 'Aisle 9');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('85', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('86', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('87', 'Aisle 1');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('88', 'Aisle 9');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('89', 'Pharmacy');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('90', 'Eggs');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('91', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('92', 'Seafood');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('93', 'Aisle 3');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('94', 'Aisle 12');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('95', 'Aisle 12');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('96', 'Aisle 6');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('97', 'Aisle 6');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('98', 'Aisle 1');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('99', 'Aisle 5');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('100', 'Deli');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('101', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('102', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('103', 'Aisle 5');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('104', 'Fresh Produce');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('105', 'Aisle 4');
INSERT INTO publix_pplaza_aisles (id, aisle) VALUES ('106', 'Aisle 3');
